### ISSUE TITLE
Create another distributed example in addition to MNIST

### ISSUE THREAD

**Issue by mhbuehler** [kubeflow/pytorch-operator#11]
Imagenet or something else from https://github.com/pytorch/examples would be good candidates.

**Comment by jose5918** [comment]
What does an E2E example include?

**Comment by mhbuehler** [comment]
Do you have a preference? I was thinking just a new training script that shows a more complex example that executes the same way MNIST currently does. I can remove the "E2E" from the issue title, unless you have other ideas.

**Comment by jose5918** [comment]
Yeah that works. If you add another example, can you look into one that has a clearer output. The current one doesn't seem to provide information as it runs

**Comment by mhbuehler** [comment]
Good idea - I'll try to incorporate more substantial output. I'd like to pick up this issue and get started, if that's alright.

**Comment by jose5918** [comment]
@mhbuehler Sounds good
