### ISSUE TITLE
I set ”cleanPodPolicy: All”, after the worker completed, no pod was deleted.

### ISSUE THREAD

**Issue by jokerwenxiao** [kubeflow/pytorch-operator#120]

**Comment by jokerwenxiao** [comment]
Name:         pytorchtest8888888888
Namespace:    kubeflow
Labels:       <none>
Annotations:  <none>
API Version:  kubeflow.org/v1alpha2
Kind:         PyTorchJob
Metadata:
  Creation Timestamp:  2018-12-23T07:36:39Z
  Generation:          1
  Resource Version:    63534810
  Self Link:           /apis/kubeflow.org/v1alpha2/namespaces/kubeflow/pytorchjobs/pytorchtest8888888888
  UID:                 7c121e62-0685-11e9-8587-a0369fb2cebe
Spec:
  Clean Pod Policy:  All
  Pytorch Replica Specs:
    Master:
      Replicas:        1
      Restart Policy:  OnFailure
      Template:
        Metadata:
          Creation Timestamp:  <nil>
        Spec:
          Containers:
            Command:
              python
              /wxwang/pytorch_dist/pytorch_dist_gloo.py
            Image:  100.2.28.186/admin/pytorch:pytorch-0.4.1-python-3.6.6
            Name:   pytorch
            Ports:
              Container Port:  23456
              Name:            pytorchjob-port
            Resources:
            Volume Mounts:
              Mount Path:  /wxwang
              Name:        pytorchtest
          Volumes:
            Host Path:
              Path:  /home/gluster-data/wxwang/pytorch/
            Name:    pytorchtest
    Worker:
      Replicas:        3
      Restart Policy:  OnFailure
      Template:
        Metadata:
          Creation Timestamp:  <nil>
        Spec:
          Containers:
            Command:
              python
              /wxwang/pytorch_dist/pytorch_dist_gloo.py
            Image:  100.2.28.186/admin/pytorch:pytorch-0.4.1-python-3.6.6
            Name:   pytorch
            Ports:
              Container Port:  23456
              Name:            pytorchjob-port
            Resources:
            Volume Mounts:
              Mount Path:  /wxwang
              Name:        pytorchtest
          Volumes:
            Host Path:
              Path:  /home/gluster-data/wxwang/pytorch/
            Name:    pytorchtest
Status:
  Conditions:
    Last Transition Time:  2018-12-23T07:36:39Z
    Last Update Time:      2018-12-23T07:36:39Z
    Message:               PyTorchJob pytorchtest8888888888 is created.
    Reason:                PyTorchJobCreated
    Status:                True
    Type:                  Created
    Last Transition Time:  2018-12-23T07:36:39Z
    Last Update Time:      2018-12-23T07:36:43Z
    Message:               PyTorchJob pytorchtest8888888888 is running.
    Reason:                PyTorchJobRunning
    Status:                True
    Type:                  Running
  Pytorch Replica Statuses:
    Master:
      Active:  1
    Worker:
      Succeeded:  3
  Start Time:     2018-12-23T07:36:43Z
Events:
  Type    Reason                   Age   From              Message
  ----    ------                   ----  ----              -------
  Normal  SuccessfulCreatePod      16h   pytorch-operator  Created pod: pytorchtest8888888888-worker-0
  Normal  SuccessfulCreatePod      16h   pytorch-operator  Created pod: pytorchtest8888888888-worker-1
  Normal  SuccessfulCreatePod      16h   pytorch-operator  Created pod: pytorchtest8888888888-worker-2
  Normal  SuccessfulCreateService  16h   pytorch-operator  Created service: pytorchtest8888888888-worker-0
  Normal  SuccessfulCreateService  16h   pytorch-operator  Created service: pytorchtest8888888888-worker-1
  Normal  SuccessfulCreateService  16h   pytorch-operator  Created service: pytorchtest8888888888-worker-2
  Normal  SuccessfulCreatePod      16h   pytorch-operator  Created pod: pytorchtest8888888888-master-0
  Normal  SuccessfulCreateService  16h   pytorch-operator  Created service: pytorchtest8888888888-master-0

**Comment by johnugeorge** [comment]
From the kubectl describe output,  job hasn't completed

**Comment by johnugeorge** [comment]
@jokerwenxiao Still seeing the issue?

**Comment by gaocegege** [comment]
I am closing the issue since it is stale
