### ISSUE TITLE
Support gang-scheduling by kube-batch 

### ISSUE THREAD

**Issue by k82cn** [kubeflow/pytorch-operator#129]
Gang-scheduling is a common requirement from training job; kube-batch supports it right now :) So open this issue to trace the discussion.

**Comment by k82cn** [comment]
@johnugeorge , what's the plan of 0.5?

**Comment by johnugeorge** [comment]
@k82cn  
Currently, gang scheduling behavior is consistent across TF and Pytorch operators. 

Are you working on  https://github.com/kubeflow/tf-operator/issues/916? This is planned for 0.5 release across operators.

**Comment by k82cn** [comment]
regarding kubeflow/tf-operator#916 , replace PDB with PodGroup is done; I'm thinking how to add some other advanced feature from kube-batch by PodGroup :). I'll do some investigation after 0.5 :)
