### ISSUE TITLE
Pytorch operator v1beta2 API

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/pytorch-operator#134]
There are couple of minor api changes that are suggested. We can incorporate all these changes in the next API version. 

Related: https://github.com/kubeflow/tf-operator/issues/935

- [x]  Requires support of Status subresource in CRD  
- [x] Add ActiveDeadlineSeconds and BackoffLimit 
- [x] Use pod group instead of PDB for gang scheduling 
- [x] Supporting multiple versions of CRD

**Comment by jlewi** [comment]
@johnugeorge Can we close this issue?

**Comment by johnugeorge** [comment]
Waiting for https://github.com/kubeflow/tf-operator/issues/550 to get merged.
/cc @richardsliu

**Comment by richardsliu** [comment]
https://github.com/kubeflow/tf-operator/pull/963 is merged now.

**Comment by johnugeorge** [comment]
All sub issues are merged. Closing the PR
/close
