### ISSUE TITLE
Label naming style inconsistent

### ISSUE THREAD

**Issue by TimZaman** [kubeflow/pytorch-operator#140]
Nit: the labels dash/underscore are inconsistent. This hurts my inner-zen 🏯 .
```
Labels:
pytorch-replica-index=0
pytorch-replica-type=master
pytorch_job_name=job2-optimizer
pytorch_job_role=master
```

**Comment by johnugeorge** [comment]
@richardsliu Should we target this in 0.5.0? It has to be fixed in tf-operator too

**Comment by richardsliu** [comment]
We should, seems like a simple fix. Inner zen is important.
