### ISSUE TITLE
Ensuring CRD requires cluster-level authority

### ISSUE THREAD

**Issue by hejiahuan1412** [kubeflow/pytorch-operator#144]
PR https://github.com/kubeflow/pytorch-operator/pull/99 ensures CRD exists when starting pytorch-operator. 

However, the CRD Checking function requires cluster-level authority which is hard to obtain mainly for safety reason. I wonder if we can use a alternative method to avoid the cluster-level authority requirement? Thanks!

**Comment by johnugeorge** [comment]
Related: https://github.com/kubeflow/tf-operator/issues/929
