### ISSUE TITLE
The Docker image used in .4.1 has multiple security issues

### ISSUE THREAD

**Issue by JavaDerek** [kubeflow/pytorch-operator#152]
There are several High security issues with gcr.io/kubeflow-images-public/pytorch-operator:v0.4.0.  I see there is a v0.5.0.  I don't know if these issues have been addressed and/or what the reverse-compatibility between this image and 0.4.1 might be.

**Comment by johnugeorge** [comment]
Could you please elaborate more ?

**Comment by johnugeorge** [comment]
@JavaDerek Can you try this newly built image gcr.io/kubeflow-ci/pytorch-operator@v0.5.0-1-gca71982

**Comment by JavaDerek** [comment]
We're still on .4.1, so we'll splice this name into the location where we found the previous name in .4.1 and hope for the best.
