### ISSUE TITLE
how could i delete this pod

### ISSUE THREAD

**Issue by younkun** [kubeflow/pytorch-operator#154]
when execute “kubectl delete  pod pytorch-dist-mnist-gloo-master-0”  and"kubectl delete  pod pytorch-dist-mnist-gloo-worker-0",after a very short time ,these 2 pods could be created .How can I delete these pods completely? thank you very much.

**Comment by gaocegege** [comment]
The pod is managed by the pytorchjob, thus you need to delete corresponding pytorchjob, then the pod will be deleted by Kubernetes GC controller.

Or you could set the https://github.com/kubeflow/pytorch-operator/blob/master/pkg/apis/pytorch/v1beta2/types.go#L58 to All, then the controller will delete when the pytorchjob is completed.

**Comment by younkun** [comment]
Thank you !This problem has been bothering me for a long time.

**Comment by younkun** [comment]
> The pod is managed by the pytorchjob, thus you need to delete corresponding pytorchjob, then the pod will be deleted by Kubernetes GC controller.
> 
> Or you could set the https://github.com/kubeflow/pytorch-operator/blob/master/pkg/apis/pytorch/v1beta2/types.go#L58 to All, then the controller will delete when the pytorchjob is completed.

Thank you !This problem has been bothering me for a long time.

**Comment by gaocegege** [comment]
Sorry about that. It is a feature implemented by the operator.

I am closing the issue now, feel free to leave comments.
