### ISSUE TITLE
Prometheus Operator for Pytorch

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/pytorch-operator#174]
Metrics being targeted to track using Prometheus: 
Report for each pod, reports on:
- [x] CPU usage
- [x] GPU usage
- [x] Memory usage
- [x] Network usage
- [x] I/O usage
- [x] Keep-Alive check
- [x] Is Leader check
2. Report TFJob metrics:
- [x] Job creation
- [x] Job deletion
- [x] Jobs created per hour
- [x] Successful job completions
- [x] Job Failures

Master issue: https://github.com/kubeflow/common/issues/22

**Comment by johnugeorge** [comment]
Closing this as all PRs are merged
