### ISSUE TITLE
Add documentation on RBAC authorizations

### ISSUE THREAD

**Issue by johanfleury** [kubeflow/pytorch-operator#182]
Hi.

I was having a look at the [`rbac.yaml` manifest](pytorch-operator/manifests/rbac.yaml) and I have trouble understanding what every authorizations are used to.

For instance, the `pytorch-operator` is granted **all accesses** to `ConfigMaps`, `PersistentVolumeClaims`, `StorageClasses`, or `Services` but as there is no explanation, one need to dig into the Go code to understand what's the purpose of these authorizations.

Could you please add a documentation on what those rights are granted for?

**Comment by johanfleury** [comment]
Also, I just found that this file might not be up to date as `pytorch-operator` was not able to update `pytorchjobs/status`:

```diff
diff --git a/manifests/rbac.yaml b/manifests/rbac.yaml
index 18cc9fa..4c0582a 100644
--- a/manifests/rbac.yaml
+++ b/manifests/rbac.yaml
@@ -17,6 +17,7 @@ rules:
   - kubeflow.org
   resources:
   - pytorchjobs
+  - pytorchjobs/status
   verbs:
   - '*'
 - apiGroups:
```

**Comment by johnugeorge** [comment]
Manifests are updated in https://github.com/kubeflow/pytorch-operator/pull/200
