### ISSUE TITLE
Use multi-stage build for pytorch operator Dockerfile

### ISSUE THREAD

**Issue by hmtai** [kubeflow/pytorch-operator#195]
Now when user build pytorch operator image,he need build the pytorch operator binary first then use the Dockerfile to build the image.

Actually this can be built with docker multi-stage build to build the image only in one docker file.

**Comment by gaocegege** [comment]
Yeah, I think so.

/cc @johnugeorge 

BTW, we should do it for tf-operator, too.

@hmtai Are you interested in the issue? I'd appreciate if you could help us.

**Comment by johnugeorge** [comment]
Closing the issue as PR is merge
/close
