### ISSUE TITLE
Push a `latest` image on postsubmit

### ISSUE THREAD

**Issue by jose5918** [kubeflow/pytorch-operator#20]
The helm chart in the repo should be up to date with the latest build right now since there are no releases. This could be accomplished by using a `latest` tag when building postsubmits and setting the helm chart image to `latest`.

**Comment by jlewi** [comment]
Kubeflow is using ksonnet not helm. So I don't think there's much value to be had in supporting helm.

Is this issue about 
- Pushing the latest helm package?
- Pushing updated docker images?
- Pushing updated ksonnet packages?

**Comment by jose5918** [comment]
I would say at this point it's just about having a release process for the docker image.  So this might be good enough https://github.com/kubeflow/pytorch-operator/pull/28.

And yeah the readme needs an update to use the ksonnet commands instead of the helm ones.

**Comment by kunmingg** [comment]
@jlewi This PR contains brief instructions for adding nightly build:
https://github.com/kubeflow/kubeflow/pull/890

https://github.com/kunmingg/kubeflow/blob/reldoc/docs_dev/releasing.md#image-auto-release
