### ISSUE TITLE
Can I use deployment.yaml in manifests directly

### ISSUE THREAD

**Issue by wynn5a** [kubeflow/pytorch-operator#205]
Hello,

Can I use deployment.yaml in manifests without change anything?
Which version of operator image should I use when my pytorchjob version is v1beta2?

Thanks for your help.

**Comment by johnugeorge** [comment]
Yes. Latest image https://github.com/kubeflow/manifests/blob/master/pytorch-job/pytorch-operator/base/kustomization.yaml  should support both v1 and v1beta2 versions

**Comment by wynn5a** [comment]
OK, Thank you @johnugeorge
