### ISSUE TITLE
Add controller-name label for Pods and services

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/pytorch-operator#211]
Since job label is renamed to common label 'job-name', controller-name is required for pods and services to distinguish the operator. 

Related: https://github.com/kubeflow/tf-operator/issues/1066

**Comment by gaocegege** [comment]
We can refer to https://github.com/kubeflow/tf-operator/pull/1067/files

**Comment by johnugeorge** [comment]
Yes. 
/assign

**Comment by johnugeorge** [comment]
Merged as part of https://github.com/kubeflow/pytorch-operator/pull/212

**Comment by johnugeorge** [comment]
Closing this issue
/close
