### ISSUE TITLE
allocating master and work on different GPU nodes

### ISSUE THREAD

**Issue by mengdong** [kubeflow/pytorch-operator#224]
When allocating master and worker on GPU nodes on GKE, I notice it is working when master and workers are on the same node, however, if some worker got allocated to a different GPU node, it will stuck on ContainerCreating stage forever.

**Comment by gaocegege** [comment]
Can you run `kubectl describe` to get the pod info and show the output here?

**Comment by mengdong** [comment]
I release it is due to a separate persistent volume issue.
