### ISSUE TITLE
add cpu/mem resource limit to worker init container causes unmarshal error

### ISSUE THREAD

**Issue by xrmzju** [kubeflow/pytorch-operator#236]
i create a configmap to customize the worker init container(add cpu/mem limits)
```shell
~/root(master) # kubectl -nkubeflow  exec -it pytorch-operator-6df7b4c9c4-47qb2 cat /etc/config/initContainer.yaml                    
- name: init-pytorch
  image: alpine:3.10
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "100m"
      memory: "100Mi"
  command: ['sh', '-c', 'until nslookup {{.MasterAddr}}; do echo waiting for master; sleep 2; done;']
```
and the pytorch controller failed to create worker pod with errors:
```shell
cannot unmarshal !!str `100m` into resource.Quantity
```
and i googled it and found this [issue](https://github.com/kubernetes/apimachinery/issues/67), so i tried replace the "gopkg.in/yaml.v2" with "github.com/kubernetes-sigs/yaml" and everything works fine. should we replace it in upstream

**Comment by xrmzju** [comment]
@gaocegege

**Comment by gaocegege** [comment]
I think we should

/cc @johnugeorge 

@xrmzju Are you interested in it? I'd appreciate if you could fix it.

**Comment by xrmzju** [comment]
> I think we should.
> 
> /cc @johnugeorge
> 
> @xrmzju Are you interested in it? I'd appreciate if you could fix it.

i'll take it. and by the way, should we replace the godep with go mod?

**Comment by gaocegege** [comment]
@xrmzju We have the plan but I did not have the bandwidth for it. If you have time, please replace it with go mod. Thanks.

**Comment by xrmzju** [comment]
> @xrmzju We have the plan but I did not have the bandwidth for it. If you have time, please replace it with go mod. Thanks.

sure, i have already replace it in my own repo. i'll open the pr soon.

**Comment by johnugeorge** [comment]
Sounds good to me. 
we can do go mod separately. we have to do it for other repos too.

**Comment by gaocegege** [comment]
Agree.

>  we can do go mod separately. we have to do it for other repos too.
