### ISSUE TITLE
Link to CRD definition is broken

### ISSUE THREAD

**Issue by sakaia** [kubeflow/pytorch-operator#254]
Link to CRD definition is broken from README.md

https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pytorch-job/pytorch-operator.libsonnet#L11

from 
https://github.com/kubeflow/pytorch-operator/blob/master/README.md

I guess CRD definition seems following directory. But I am not sure
https://github.com/kubeflow/manifests/tree/0fa9c0126f62392d1c27f31711e513b22ef28cbc/pytorch-job

or 

https://github.com/kubeflow/kubeflow/blob/master/releasing/releaser/components/pytorch-operator.jsonnet

**Comment by Jeffwan** [comment]
This is expected, you can install from `manifest` folder now and if you are looking for kubeflow distribution, check

https://github.com/kubeflow/manifests/tree/master/pytorch-job
