### ISSUE TITLE
How to run single-machine job？

### ISSUE THREAD

**Issue by jiaqianjing** [kubeflow/pytorch-operator#278]
I found  that the value of master can only be set to 1 . Can I only run distributed job by pytorch-operator ?

**Comment by gaocegege** [comment]
No, you can have 1 Master to run local training jobs.

/cc @johnugeorge

**Comment by jiaqianjing** [comment]
> No, you can have 1 Master to run local training jobs.
> 
> /cc @johnugeorge

ok, I had got it

**Comment by gaocegege** [comment]
Feel free to post questions here if there is any problem when you run local training jobs with pytorch-operator.

**Comment by jiaqianjing** [comment]
> Feel free to post questions here if there is any problem when you run local training jobs with pytorch-operator.

3q. By the way, could I have your Wechat?

**Comment by gaocegege** [comment]
Please tell me your mail address, I will send to you.

**Comment by jiaqianjing** [comment]
> Please tell me your mail address, I will send to you.

jiaqianjing@gmail.com or jiaqianjing1992@163.com

**Comment by gaocegege** [comment]
sent to jiaqianjing@gmail.com
