### ISSUE TITLE
Where are the pytorch-crd and pytorch-operator YAML files?

### ISSUE THREAD

**Issue by g-karthik** [kubeflow/pytorch-operator#281]
For mpi-operator, the commands are as simple as:

`kubectl apply -f https://raw.githubusercontent.com/kubeflow/mpi-operator/master/deploy/v1alpha2/mpi-operator.yaml `

where the official mpi-operator yaml files are hosted on the corresponding repo.

Where exactly is the pytorch-operator yaml hosted? I'm looking for a simple way to apply it with kubectl without needing to install/setup kubeflow.

**Comment by 535727234** [comment]
crd:https://github.com/kubeflow/pytorch-operator/blob/master/manifests/crd.yaml
deployment:https://github.com/kubeflow/pytorch-operator/blob/master/manifests/deployment.yaml

**Comment by g-karthik** [comment]
@535727234 thanks! To be clear, does this mean one does not need to install kubeflow and just using `kubectl apply` with those YAML files is sufficient?

Because [here](https://www.kubeflow.org/docs/components/training/pytorch/) it says that kubeflow and kustomize need to be installed first.

```
export KF_DIR=<your Kubeflow installation directory>
cd ${KF_DIR}/kustomize
kubectl apply -f pytorch-job-crds.yaml
kubectl apply -f pytorch-operator.yaml
```

**Comment by gaocegege** [comment]
Yeah, you do not need to install kubeflow if you just want to use pytorch-operator.

**Comment by gaocegege** [comment]
Kubeflow docs provide a unified approach to install kubeflow components. But it is not the only way.

**Comment by gaocegege** [comment]
@535727234 Thanks for your reply!
