### ISSUE TITLE
PyTorchJob CRD definition link is broken

### ISSUE THREAD

**Issue by sakaia** [kubeflow/pytorch-operator#284]
In Following document, link to CRD definition is broken.(it causes 404 error)
https://github.com/kubeflow/pytorch-operator/blob/master/README.md

I guess it should be linked to 

https://www.kubeflow.org/docs/reference/pytorchjob/v1/
or
https://github.com/kubeflow/website/blob/d0bd0e031453d12e704d0636f9ad192c866a327c/content/en/docs/reference/pytorchjob/v1/pytorch.md

**Comment by gaocegege** [comment]
Thanks for the issue. Now it works.
