### ISSUE TITLE
how to create a local non-distributed training

### ISSUE THREAD

**Issue by houz42** [kubeflow/pytorch-operator#287]
as defined in the crd, worker replicas must >= 1, and master replica == 1, so how to create such a training job runs on single node?

https://github.com/kubeflow/pytorch-operator/blob/eba73411bc03d70b72dcab623aa7a01c14f811d4/manifests/crd.yaml#L37

**Comment by houz42** [comment]
@gaocegege you metioned in another issue (https://github.com/kubeflow/pytorch-operator/issues/278#issuecomment-642353290) that:

> you can have 1 Master to run local training jobs

But I just can not create a pytorchjob without worker.

**Comment by gaocegege** [comment]
Then you can try to create one worker job.

**Comment by houz42** [comment]
> Then you can try to create one worker job.

A pytorchjob with no master? can't create it neither, master replica must be 1

**Comment by gaocegege** [comment]
I tried to create one master job and it works. Can you explain more about `But I just can not create a pytorchjob without worker.`

Is there any error during the run?

**Comment by houz42** [comment]
> Is there any error during the run?

I finally realized it was my fault. I dit not create "a pytorchjob with only 1 master", but "a pytorchjob with 1 master and 0 worker", which was denied during validation.

Sorry for my mistake and thanks for your patient.
