### ISSUE TITLE
Add an example for DistributedDataParallel

### ISSUE THREAD

**Issue by jose5918** [kubeflow/pytorch-operator#29]
- Add an example for DistributedDataParallel or edit a current example to use this functionality.
- Add an example for new DistributedDataParallel CPU https://github.com/pytorch/pytorch/pull/5919/files in Pytorch v0.4.0

**Comment by jlewi** [comment]
I'm marking this P1 because I think a minimal example is required in order to have the pytorch operator ready as part of our 0.2 release.

**Comment by jlewi** [comment]
@johnugeorge What's the status of this? Do we have a data parallel example? If not should we try to add one as part of 0.3. or 0.4?
