### ISSUE TITLE
'./pytorch_job_sendrecv.yaml' missing in  pytorch-operator/examples/smoke-dist

### ISSUE THREAD

**Issue by Lyken17** [kubeflow/pytorch-operator#291]
In [smoke-dist](https://github.com/kubeflow/pytorch-operator/tree/master/examples/smoke-dist), it says 

Create the PyTorch job
```
kubectl create -f ./pytorch_job_sendrecv.yaml
```

But the `pytorch_job_sendrecv.yaml` is not there.

**Comment by chenwenyan** [comment]
Do you have solved it? It seems that the YAML file is not here yet.

**Comment by Lyken17** [comment]
Unfortuantely, no

**Comment by gaocegege** [comment]
cc @johnugeorge
