### ISSUE TITLE
pytorch-operator pod CheckCRDExist failed

### ISSUE THREAD

**Issue by myonlyzzy** [kubeflow/pytorch-operator#294]
I use manifests dir [yaml](https://github.com/kubeflow/pytorch-operator/tree/master/manifests) file create pytorch-operator deployment, but pod status is error. 

```
{"filename":"app/server.go:73","level":"info","msg":"EnvKubeflowNamespace not set, use default namespace","time":"2020-08-03T09:53:49Z"}
{"filename":"app/server.go:78","level":"info","msg":"[API Version: v1 Version: v0.1.0-alpha Git SHA: Not provided. Go Version: go1.12 Go OS/Arch: linux/amd64]","time":"2020-08-03T09:53:49Z"}
W0803 09:53:49.298085       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"filename":"pytorch-operator.v1/main.go:33","level":"info","msg":"Setting up client for monitoring on port: 8443","time":"2020-08-03T09:53:49Z"}
{"filename":"app/server.go:200","level":"error","msg":"the server could not find the requested resource (get pytorchjobs.kubeflow.org)","time":"2020-08-03T09:53:49Z"}
{"filename":"app/server.go:102","level":"info","msg":"CRD doesn't exist. Exiting","time":"2020-08-03T09:53:49Z"}
```
k8s version: Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}.

**Comment by gaocegege** [comment]
Did you create the CRD?

**Comment by myonlyzzy** [comment]
> Did you create the CRD?

I create crd but checkCRD, I think the problem maybe image. use gcr.io/kubeflow-images-public/pytorch-operator:latest or  image that build form  Dockerfile   ok.
