### ISSUE TITLE
can I use gpus on specific node to train

### ISSUE THREAD

**Issue by lwj1980s** [kubeflow/pytorch-operator#310]
My k8s Cluster:
master: 4  GTX 1080ti
node1: 4 RTX 2080
node2: 4 RTX 2080

When I  run a pytorchJob， it seems that kubeflow select the gpu automatically. What should I do(write config item on the deploy.yaml or some way else)  if I want to use gpus on node1 or node2 specifically，but not master.

**Comment by Jeffwan** [comment]
You need to use node affinity/label to choose your right GPU. 

https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/

**Comment by lwj1980s** [comment]
> You need to use node affinity/label to choose your right GPU.
> 
> https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/

Thanks very much！
