### ISSUE TITLE
Does pytorch-opterator just simplified the use of nn.parallel.DistributedDataParallel on multi nodes of multi gpu？

### ISSUE THREAD

**Issue by lwj1980s** [kubeflow/pytorch-operator#311]
despite of the characters of k8s,  could I considered that pytorch-opterator is kind of one-key deploy of  pytorch DistributedDataParallel  training？

**Comment by gaocegege** [comment]
Yeah, I think you can. But we do not just deploy, we maintain the lifecycle of the training jobs.

**Comment by lwj1980s** [comment]
> Yeah, I think you can. But we do not just deploy, we maintain the lifecycle of the training jobs.

Thank you very much，I have got it
