### ISSUE TITLE
Please create v1.2-branch

### ISSUE THREAD

**Issue by SatwikBhandiwad** [kubeflow/pytorch-operator#314]

**Comment by gaocegege** [comment]
Can you please explain more about this issue? Thanks

**Comment by SatwikBhandiwad** [comment]
> Can you please explain more about this issue? Thanks

It would be helpful if you can create a branch mapping to kubeflow v1.2.0 [release](https://github.com/kubeflow/kubeflow/releases/tag/v1.2.0) similar to [v1.1-branch](https://github.com/kubeflow/pytorch-operator/tree/v1.1-branch)

**Comment by Jeffwan** [comment]
@SatwikBhandiwad The pattern changes a little bit. We will not create release branch for every kubeflow release.  all operator will have their own versions in the future. Kubeflow will just integrate manifest to it's umbrella. 

Feel free to reopen if you need more details
