### ISSUE TITLE
is there a simpler way to install pytorch-operator

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/pytorch-operator#328]
is there a simpler way to install, no need to install kubeflow, only provide yaml like this [mpi-operator.yaml](https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1alpha2/mpi-operator.yaml)

**Comment by gaocegege** [comment]
Currently, you can use https://github.com/kubeflow/pytorch-operator/tree/master/manifests to deploy pytorch operator. It is the config for kustomize.

**Comment by tingweiwu** [comment]
@gaocegege Thanks a lot~~
