### ISSUE TITLE
`init-pytorch` init container image configurable

### ISSUE THREAD

**Issue by apatil4** [kubeflow/pytorch-operator#339]
We are trying to launch a distributed training job and saw that the init container for workers were having a `imagePullBackOff` error because they were trying access the `alpine:3.10` image from the docker hub and we were hitting the docker rate limits on image pull. 

```
The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.
NOTE: Docker Pro and Docker Team accounts enable 5,000 pulls in a 24 hour period from Docker Hub.  
```
We were wondering if that image location is configurable and maybe we can copy the alpine image into our private ECR repo and reference it.

**Comment by johnugeorge** [comment]
Yes. you could configure using `init-container-image` flag

https://github.com/kubeflow/pytorch-operator/blob/master/cmd/pytorch-operator.v1/app/options/options.go#L80

**Comment by apatil4** [comment]
Thanks. Is there an example that you can point me to that uses the flag or similar flags.
I found one here - https://github.com/kubeflow/pytorch-operator/blob/master/examples/mnist/v1/pytorch_job_mnist_gloo.yaml#L18 but not sure if it was correct.
Also, should that option be in both master and worker specs?

**Comment by johnugeorge** [comment]
@apatil4  No. This is the flag to the pytorch controller. You have to configure it here https://github.com/kubeflow/pytorch-operator/blob/master/manifests/base/deployment.yaml#L21 during deployment.

**Comment by apatil4** [comment]
Thanks for the pointer. That did help and was able to use the option `init-container-image`. Closing the issue
