### ISSUE TITLE
Preserving git history for tf-operator

### ISSUE THREAD

**Issue by jose5918** [kubeflow/pytorch-operator#4]
I have a branch that preserves the git history from TF operator here https://github.com/jose5918/pytorch-operator/tree/initial-operator, but it is considered an entirely different git history so I can't merge.

If anyone knows the correct way to preserve the history that would be helpful so that the changes made between the pytorch and tf operators is more transparent.

**Comment by gaocegege** [comment]
I think there is no need to keep the git history from tf-operator.

If you want to keep it, I think we can squash all commits in tf operator into one and commit it to this repo, then commit new code.

**Comment by jose5918** [comment]
Alright, I'll probably leave that branch open then in case people want to look.

**Comment by jlewi** [comment]
Can we close this issue?

**Comment by johnugeorge** [comment]
Not relevant anymore
/close
