### ISSUE TITLE
Support cross compile for image build.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/pytorch-operator#42]
Currently if we run [build_image.sh](https://github.com/kubeflow/pytorch-operator/blob/master/build_image.sh) from OSX, the generated go binary might not work on linux. 
We want to support corss compile.

**Comment by johnugeorge** [comment]
@kunmingg  Shall we fix env settings GOOS=linux GOARCH="amd64 for go build?

**Comment by NikhilKanda** [comment]
I'm wondering to know if there's a way to cross compile Pytorch on Allwinner platform (AArch64 processor). Leads are greatly appreciated.

**Comment by johnugeorge** [comment]
Closing this issue as per comment https://github.com/kubeflow/pytorch-operator/issues/42#issuecomment-421086420
