### ISSUE TITLE
Can PyTorch share implementation with TfJob operator?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pytorch-operator#50]
v1alpha2 made significant improvements to the TFJob operator implementation.

Can we refactor the implementation into a library that can be reused by TFJob operator?

**Comment by gaocegege** [comment]
@jlewi 
I think @ankushagarwal 's proposal could solve the problem.

**Comment by jlewi** [comment]
This issue is in reference to that proposal.

**Comment by jlewi** [comment]
@johnugeorge is actively working on refactoring the code to share implementation. So the answer to the question is "yes". 

Marking this as fixed; we can open up more scoped issues as needed.

**Comment by TimZaman** [comment]
Which proposal were you referring to?
