### ISSUE TITLE
[discussion] Need for 'Master' replica type?

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/pytorch-operator#55]
Currently, there are two replica types in Pytorch -' Master' and 'Worker'  Do we really need 'Master'  replica type?  From the pytorch distributed description, master is the worker with the rank 0(first worker)   From @jose5918, I got to know that it was kept to indicate the difference between a 'master' and 'worker' incase of a distributed job. 
Even if we keep master, no of master replicas has to be always set to 1.   Currently, For a local job, config has 1 master and 0 workers,  and for a distributed job, config has 1 master and n workers
if we have just 'worker' as type(without 'master' type),  config will have 1 worker for a local job and config will have n workers for a distributed job.

We can do it either way.  Looking for suggestions/thoughts which would bring more clarity and ease of use

@gaocegege @jlewi @jose5918

**Comment by johnugeorge** [comment]
From slack conversations,

 we will keep the way it is for now. We can revisit if there is any need in the future.  For now, Master type with replica 1 will be mandatory for every PytorchJob. 

Closing this issue. 
/close

**Comment by johanfleury** [comment]
Could you elaborate on this slack conversation?

I find the current spec a bit disturbing (master `replicas` limited to 1 and only 1 for instance) and as far as I know, the current implementation doesn't have a specific code path for managing the master pod (it starts all the pods at the same time for instance).
