### ISSUE TITLE
Add example for Gloo backend

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/pytorch-operator#67]
Related to #7

**Comment by royxue** [comment]
I just tested this gloo backend could work, no need to change the existed mnist test alot.
Just replace backend, add GPU support, and add `destroy_process_group`.

If you need help, I could make a PR

**Comment by royxue** [comment]
However, hmmm which is kinda strange, the gloo can only work with v1alpha2 version, but failed on v1alpha1

**Comment by gaocegege** [comment]
We do not maintain v1alpha1 anymore, thus it works for us. IMO.

**Comment by royxue** [comment]
There is still one issue left for gloo backend I was looking into.
The worker pod could reach `completed` status after `destroy_process_group`. But the master pod cannot, and will always restart.

This might be related to the pytorch version and NCCL version.

**Comment by gaocegege** [comment]
We can dive into the issue, if we cannot fix it, we can refer to tf-operator and add a cleanpodpolicy to delete the master pod after the job is finished.

**Comment by johnugeorge** [comment]
@royxue Why is the master pod restart? Currently RestartPolicy is OnFailure.  Does it fail?

**Comment by royxue** [comment]
yep, it will throw out an error, which would be regarded as failed. I could provide the error info later.

Also, for example, if you didnt call `destroy_process_group`, gloo would throw the `EnForceNotMet`  error. as shown in (https://github.com/pytorch/pytorch/issues/2530) which would cause all pod restarted.

**Comment by royxue** [comment]
@johnugeorge 
The error is
```
terminate called after throwing an instance of 'std::system_error'
  what():  Software caused connection abort
```

**Comment by johnugeorge** [comment]
Looks like pytorch bug

**Comment by royxue** [comment]
I think pytorch didnt stop the gloo process correctly when distributed training finished.

**Comment by johnugeorge** [comment]
This issue is not reproduced in pytorch:04
