### ISSUE TITLE
[examples] Add an example for PyTorch 0.4

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/pytorch-operator#69]
We have an example using PyTorch v0.2, which is released a year ago. I think we could add a v0.4 example.

When I tried to use the dist MNIST code in examples and v0.4 image to run it, the pods are failed.

**Comment by johnugeorge** [comment]
which pytorch version did you use ? https://hub.docker.com/r/pytorch/pytorch/tags/

**Comment by gaocegege** [comment]
0.4_cuda9_cudnn7

**Comment by johnugeorge** [comment]
@gaocegege  I am not able to reproduce the error. I tried dist-mnist example( https://github.com/kubeflow/pytorch-operator/tree/master/examples/dist-mnist ) with both pytorch:0.4_cuda9_cudnn7 and pytorch:latest

Job was successful. Are you using default configuration?  Which example did you use?

**Comment by gaocegege** [comment]
I will try again. I use https://github.com/caicloud/ciao to set up a PyTorchJob in Jupyter Notebook, maybe the bug is in my code.
