### ISSUE TITLE
[test] Establish CI system for this repo

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/pytorch-operator#8]
I think we should establish CI (Travis and prow or only prow) for maintenance.

**Comment by jose5918** [comment]
I will start setting up Prow so that other people can start working on this as well

**Comment by jose5918** [comment]
https://github.com/kubernetes/test-infra/pull/7313

**Comment by jose5918** [comment]
@gaocegege Can we close this? Testing should be in place for both Travis and prow

**Comment by gaocegege** [comment]
Sorry for the late reply, feel free to close it since we already imported it
